service: simulation-vr-test1

provider:
  name: aws
  region: ap-northeast-1
  memorySize: 4096
  timeout: 240

functions:
  samplefunc:
    image: "<YOUR ID>.dkr.ecr.ap-northeast-1.amazonaws.com/lambda-python-docker-sample1@sha256:***********"
    events:
      - http:
          path: digit_distdata/{dim}
          method: any
      - http:
          path: financial_distdata/{dim}
          method: any
